# Spring data
spring:
    datasource:
        url: ${JDBC_DATASOURCE_URL}
    jpa:
        open-in-view: false 
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: ${HIBERNATE_SHOW_SQL:true}
        properties:
            hibernate:
                generate_statistics: ${HIBERNATE_STATISTICS:false}
                temp:
                    use_jdbc_metadata_defaults: false

# Clients
userinfo:
    service:
        name: userinfo-service
        url: ${USERINFO_SERVICE_URL:https://user-info.herokuapp.com}

# SwaggerConfig
springdoc:
    api-docs:
        path: /api-doc
    swagger-ui:
        path: /swagger-ui.html

#Deploy config(heroku)
server:
    port: ${PORT}