# Spring data
spring:
    datasource:
        url: jdbc:${DATASOURCE_URL}
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true

# Clients
userinfo:
    service:
        name: userinfo-service
        url: ${USERINFO_SERVICE_URL:https://user-info.herokuapp.com}

# SwaggerConfig
springdoc:
    api-docs:
        path: /api-doc
    swagger-ui:
        path: /swagger-ui.html

#Deploy config(heroku)
server:
    port: ${PORT}